#!/usr/bin/env sh
set -e

. "$(dirname "$0")/lib/functions.sh"

current_branch="$(git symbolic-ref --short HEAD)"
base_branch="$(get_base_branch)"
repo_root="$(git rev-parse --show-toplevel)"

# Run checks only when there are changes relative to the base branch and only for the specific directories.
if ! git diff --quiet "$base_branch" "$current_branch" --name-only | grep '^packages/backend/'; then
  cd "$repo_root/packages/backend"
  bun run cf-typegen
  bun run build:types
  bun run type-check
  bun run lint
  bun run test
fi

# Run checks only when there are changes relative to the base branch and only for the specific directories.
if ! git diff --quiet "$base_branch" "$current_branch" --name-only | grep '^packages/mobile/'; then
  cd "$repo_root/packages/mobile"
  bun run type-check
  bun run lint
  # bun run test
fi
